### ISSUE TITLE
Errors in visualizations

### ISSUE THREAD

**Issue by tratchel** [wwalker0307/ElasticMARC#1] opened 2018-03-22 15:10 UTC
Hi wwalker0307,
First off, thanks so much for providing this.  We've been working to get DMARC data ingested in Elastic ourselves and your work saved us a significant amount of time (and likely headaches).  

After importing the visualizations and dashboards, there are a few errors that we ran into.

Errors I get in the console: 

> - “Could not locate that index-pattern-field (id: authresult.spf_domain.keyword)”
> - “Could not locate that index-pattern-field (id: authresult.dkim_result.keyword)”
> - “Could not locate that visualization (id: 9627e210-0fba-11e8-8dc5-e141d701899b)”  

The first two were simple fixes, I just updated the id: from `authresult.blah ` to `auth_result.blah` and they worked perfectly.  

The last one for a missing visualization I'm less sure about.  The error we get is below, so I'm not sure what visualization it's trying to load

![viz_err](https://user-images.githubusercontent.com/37665112/37778615-5ddc7094-2db8-11e8-80c9-2dacc0d234d0.png)

But judging from the screenshot on the ElasticMARC repo it looks like Top Senders (IP)

![dashboard](https://user-images.githubusercontent.com/37665112/37778690-8ddff4d2-2db8-11e8-8679-44bbabee4b15.JPG)

When I look at the ElasticMARC/kibana/visuals/DMARCVisuals.json I see visualizations for the other **Top Senders (x)** visuals, but nothing for Top Senders (IP) so I think it just might be missing.

**Comment by wwalker0307** [comment] 2018-03-23 03:05
Ya, I made a few last minute changes across different deployments that lead to the disparity in the authresult/auth_result field name.  I've since made some changes and broken the visualizations into three separate files.  Would you mind grabbing the new ones and importing them into your setup.  I believe the issue is resolved in them.  I also made a fix to another the Top Senders (IP) table, that while missing, was aggregating the wrong number.

**Closed** 2018-03-27 12:58 UTC
